// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genderAlgo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenderResponse_Status_Code int32

const (
	GenderResponse_Status_OK  GenderResponse_Status_Code = 0
	GenderResponse_Status_ERR GenderResponse_Status_Code = 1
)

var GenderResponse_Status_Code_name = map[int32]string{
	0: "OK",
	1: "ERR",
}

var GenderResponse_Status_Code_value = map[string]int32{
	"OK":  0,
	"ERR": 1,
}

func (x GenderResponse_Status_Code) String() string {
	return proto.EnumName(GenderResponse_Status_Code_name, int32(x))
}

func (GenderResponse_Status_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83f6cfb04dc4a1f6, []int{1, 0, 0}
}

type GenderRequest struct {
	VoiceId              string   `protobuf:"bytes,1,opt,name=voiceId,proto3" json:"voiceId,omitempty"`
	StartTime            uint64   `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint64   `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenderRequest) Reset()         { *m = GenderRequest{} }
func (m *GenderRequest) String() string { return proto.CompactTextString(m) }
func (*GenderRequest) ProtoMessage()    {}
func (*GenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83f6cfb04dc4a1f6, []int{0}
}

func (m *GenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderRequest.Unmarshal(m, b)
}
func (m *GenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderRequest.Marshal(b, m, deterministic)
}
func (m *GenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderRequest.Merge(m, src)
}
func (m *GenderRequest) XXX_Size() int {
	return xxx_messageInfo_GenderRequest.Size(m)
}
func (m *GenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenderRequest proto.InternalMessageInfo

func (m *GenderRequest) GetVoiceId() string {
	if m != nil {
		return m.VoiceId
	}
	return ""
}

func (m *GenderRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GenderRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GenderResponse struct {
	Status               *GenderResponse_Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Gender               string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GenderResponse) Reset()         { *m = GenderResponse{} }
func (m *GenderResponse) String() string { return proto.CompactTextString(m) }
func (*GenderResponse) ProtoMessage()    {}
func (*GenderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83f6cfb04dc4a1f6, []int{1}
}

func (m *GenderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderResponse.Unmarshal(m, b)
}
func (m *GenderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderResponse.Marshal(b, m, deterministic)
}
func (m *GenderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderResponse.Merge(m, src)
}
func (m *GenderResponse) XXX_Size() int {
	return xxx_messageInfo_GenderResponse.Size(m)
}
func (m *GenderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenderResponse proto.InternalMessageInfo

func (m *GenderResponse) GetStatus() *GenderResponse_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GenderResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type GenderResponse_Status struct {
	Code                 GenderResponse_Status_Code `protobuf:"varint,1,opt,name=code,proto3,enum=proto.GenderResponse_Status_Code" json:"code,omitempty"`
	Msg                  string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GenderResponse_Status) Reset()         { *m = GenderResponse_Status{} }
func (m *GenderResponse_Status) String() string { return proto.CompactTextString(m) }
func (*GenderResponse_Status) ProtoMessage()    {}
func (*GenderResponse_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_83f6cfb04dc4a1f6, []int{1, 0}
}

func (m *GenderResponse_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenderResponse_Status.Unmarshal(m, b)
}
func (m *GenderResponse_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenderResponse_Status.Marshal(b, m, deterministic)
}
func (m *GenderResponse_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenderResponse_Status.Merge(m, src)
}
func (m *GenderResponse_Status) XXX_Size() int {
	return xxx_messageInfo_GenderResponse_Status.Size(m)
}
func (m *GenderResponse_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_GenderResponse_Status.DiscardUnknown(m)
}

var xxx_messageInfo_GenderResponse_Status proto.InternalMessageInfo

func (m *GenderResponse_Status) GetCode() GenderResponse_Status_Code {
	if m != nil {
		return m.Code
	}
	return GenderResponse_Status_OK
}

func (m *GenderResponse_Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.GenderResponse_Status_Code", GenderResponse_Status_Code_name, GenderResponse_Status_Code_value)
	proto.RegisterType((*GenderRequest)(nil), "proto.GenderRequest")
	proto.RegisterType((*GenderResponse)(nil), "proto.GenderResponse")
	proto.RegisterType((*GenderResponse_Status)(nil), "proto.GenderResponse.Status")
}

func init() { proto.RegisterFile("genderAlgo.proto", fileDescriptor_83f6cfb04dc4a1f6) }

var fileDescriptor_83f6cfb04dc4a1f6 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x4b, 0x41, 0x90, 0x51, 0x1b, 0x32, 0xf1, 0x0f, 0x36, 0x9a, 0x54, 0x4e, 0x3d, 0x71,
	0x40, 0x3d, 0x7a, 0x30, 0xc6, 0x18, 0x63, 0xa2, 0xc9, 0xe2, 0xdd, 0x20, 0x3b, 0x41, 0x8c, 0xb0,
	0x95, 0xdd, 0xf6, 0x43, 0xfa, 0xa9, 0x0c, 0xb3, 0x70, 0xd0, 0x18, 0x4f, 0x30, 0xef, 0xfd, 0xf2,
	0xde, 0xec, 0x40, 0x54, 0x51, 0x2b, 0xa9, 0xbb, 0xfe, 0xa8, 0x54, 0xba, 0xea, 0x94, 0x51, 0xb8,
	0xc5, 0x9f, 0xa4, 0x84, 0xbd, 0x3b, 0xb6, 0x04, 0x7d, 0xae, 0x49, 0x1b, 0x8c, 0x21, 0xd8, 0xa8,
	0xba, 0xa4, 0x7b, 0x19, 0x3b, 0x0b, 0x67, 0x19, 0x8a, 0x71, 0xc4, 0x53, 0x00, 0x6d, 0x8a, 0xce,
	0xbc, 0x98, 0xba, 0xa1, 0x78, 0xba, 0x70, 0x96, 0x9e, 0x08, 0x59, 0x79, 0xae, 0x1b, 0xc2, 0x63,
	0xd8, 0xa6, 0x56, 0x5a, 0xd3, 0x65, 0x33, 0xa0, 0x56, 0xf6, 0x56, 0xf2, 0xe5, 0xc0, 0x6c, 0x6c,
	0xd1, 0x2b, 0xd5, 0x6a, 0xc2, 0x0b, 0xf0, 0xb5, 0x29, 0xcc, 0x5a, 0x73, 0xcb, 0x4e, 0x76, 0x62,
	0xd7, 0x4a, 0x7f, 0x62, 0x69, 0xce, 0x8c, 0x18, 0x58, 0x3c, 0x04, 0xdf, 0x3e, 0x84, 0xeb, 0x43,
	0x31, 0x4c, 0xf3, 0x77, 0xf0, 0x2d, 0x89, 0x97, 0xe0, 0x95, 0x4a, 0x12, 0xa7, 0xce, 0xb2, 0xb3,
	0xff, 0x52, 0xd3, 0x1b, 0x25, 0x49, 0x30, 0x8e, 0x11, 0xb8, 0x8d, 0xae, 0x86, 0xd4, 0xfe, 0x37,
	0x39, 0x02, 0xaf, 0xf7, 0xd1, 0x87, 0xe9, 0xd3, 0x43, 0x34, 0xc1, 0x00, 0xdc, 0x5b, 0x21, 0x22,
	0x27, 0x7b, 0x1c, 0x2f, 0x96, 0x53, 0xb7, 0xa9, 0x4b, 0xc2, 0x2b, 0xd8, 0xcd, 0xa9, 0xe8, 0xca,
	0x37, 0x2b, 0xe3, 0xfe, 0xaf, 0x52, 0xbe, 0xeb, 0xfc, 0xe0, 0xcf, 0x55, 0x92, 0xc9, 0xab, 0xcf,
	0xfa, 0xf9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x28, 0xfe, 0xee, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GenderServiceClient is the client API for GenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenderServiceClient interface {
	SearchGender(ctx context.Context, in *GenderRequest, opts ...grpc.CallOption) (*GenderResponse, error)
}

type genderServiceClient struct {
	cc *grpc.ClientConn
}

func NewGenderServiceClient(cc *grpc.ClientConn) GenderServiceClient {
	return &genderServiceClient{cc}
}

func (c *genderServiceClient) SearchGender(ctx context.Context, in *GenderRequest, opts ...grpc.CallOption) (*GenderResponse, error) {
	out := new(GenderResponse)
	err := c.cc.Invoke(ctx, "/proto.GenderService/SearchGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenderServiceServer is the server API for GenderService service.
type GenderServiceServer interface {
	SearchGender(context.Context, *GenderRequest) (*GenderResponse, error)
}

// UnimplementedGenderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGenderServiceServer struct {
}

func (*UnimplementedGenderServiceServer) SearchGender(ctx context.Context, req *GenderRequest) (*GenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGender not implemented")
}

func RegisterGenderServiceServer(s *grpc.Server, srv GenderServiceServer) {
	s.RegisterService(&_GenderService_serviceDesc, srv)
}

func _GenderService_SearchGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServiceServer).SearchGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GenderService/SearchGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServiceServer).SearchGender(ctx, req.(*GenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GenderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GenderService",
	HandlerType: (*GenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchGender",
			Handler:    _GenderService_SearchGender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genderAlgo.proto",
}
